### ISSUE TITLE
Trust property?

### ISSUE THREAD

**Issue by theri** [theri/draft-enghardt-panrg-path-properties#28]
Going back to comments/discussion at IETF 106, we might also want to think about modeling trust, i.e., how much a certain path element trusts another.
However, I don't think we should do at least the trust part without a threat model, and we are not defining this threat model ourselves. Apparently, others are defining a threat model, so maybe this is something to revisit once that threat model exists. 
Joachim said: "You're not defining a threat model but others are […] and it might be interesting to characterize a path wrt whether it is liable to a threat"

**Comment by cyrill-k** [comment]
See #27

**Comment by theri** [comment]
Could add one more example to the part where we discuss the threat model (in the Security considerations)
