### ISSUE TITLE
Be clearer on physical layer properties

### ISSUE THREAD

**Issue by theri** [theri/draft-enghardt-panrg-path-properties#3]
With physical layer properties such as modulation rate:
Be either more abstract (i.e., not talk about 802.11 but just in general) or more specific (i.e., add satellite network properties).
The notes are not really clear on this...

**Comment by theri** [comment]
After listening to the recording again and reading the mentioned RFC 8175 (Dynamic Link Exchange Protocol, DLEP), I'm fairly certain that they wanted us to be more abstract.
DLEP specifies a set of metrics that should apply to different physical and link layer protocols, i.e., to 802.11 and satellite links and others. They are specifically defined on a layer 2 domain, so for our path, I guess this would be the first hop.
RFC 8175 does not specify HOW exactly those metrics are calculated, but what they mean and what format they have. 
They have "per destination" metrics and "per session" (for all destinations). I guess for us, "per destination" is enough, because we probably want to specify these as properties for a single hop among our path. 

So, some of their metrics that might be relevant input for our properties:

- Maximum data rate (receive/transmit) - Section 13.12 and 13.13 - this is the theoretical maximum data rate, in bits per second, that can be achieved on this link (i.e., the first hop) for receiving or transmitting traffic
- Current data rate (receive/transmit) - Section 13.14 and 13.15 - this is the rate at which the link is currently operating, in bits per second, for receiving or transmitting traffic
- Latency - Section 13.16 - transmission delay on the link, in microseconds
- Relative link quality (receive/transmit) - Section 13.18 and 13.19 - this indicates link stability, with 0 = least stable = metrics are likely to change a lot, and 100 = most stable = metrics are likely to stay stable
- MTU - Section 13.20 - maximum size of an IP packet in Bytes that can be transmitted without fragmentation, including IP headers, but excluding lower-layer headers

What we have right now in the draft is:
- Wireless Signal strength: Power level of the wireless signal being received. Lower signal strength, relative to the same noise floor, is correlated with higher bit error rates and lower modulation rates.
- Wireless Modulation Rate: Modulation bitrate of the wireless signal. The modulation rate determines how many bytes are transmitted within a symbol on the wireless channel. A high modulation rate leads to a higher possible bitrate, given sufficient signal strength.
- Wireless Channel utilization: Percentage of time during which there is a transmission on the wireless medium. A high channel utilization indicates a congested wireless network.

I guess because it says "Wireless", they took it to mean 802.11-specific, and I guess by "modulation rate" I meant the same as "current data rate" in RFC 8175.

I'm wondering why Signal Strength is missing from RFC 8175, as this is something that exists for most relevant protocols I guess, but in itself, Signal Strength is not really useful. In the end, I guess it mostly influences the available data rate, so if we have this one covered...

So I guess we can **substitute our "modulation rate" by "maximum data rate" and "current data rate"**, and we can **drop "Signal Strength"**. 
**Maybe drop "Utilization" as well**, as this presumes a shared medium, which does not apply to all link layers, and I'm not sure how useful it is?

Also, I guess we should **make our definition of MTU more specific**, but I think our MTU should be defined end-to-end on the path, not just on the first hop.

I'm not sure we need another Latency that only applies on the first hop. Let's see how we define our "path latency" in relation to the formal definition of a path that we come up with.

Also, relative link quality I'm not quite sure we need.

Any opinions on this?

I'm planning to prepare a Pull Request for this next week.

**Comment by cyrill-k** [comment]
I think it makes sense to substitute modulation rate by maximum data rate & available data rate.

Since the overall goal of this document is to list properties that are useful for protocols using information about paths (path awareness), we can probably drop signal strength as the properties it influences (available data rate & loss rate) are what is mostly relevant.

Dropping Utilization is fine for me, since we have available & maximum data rate which together can be used to approximate Utilization.

I also think an end-to-end MTU is more useful than a single-hop MTU.

**Comment by theri** [comment]
Closed via #4
